version: v{build}

image: Visual Studio 2019

clone_folder: c:\uncompyle6-builds
shallow_clone: true
clone_depth: 1


install:
- cmd: >-
    C:\Python38-x64\python.exe -m pip install pyoxidizer


build_script:
- cmd: pyoxidizer build --release

after_build:
 - 7z a uncompyle6-x86_64.7z C:\uncompyle6-builds\build\x86_64-pc-windows-msvc\release\install\uncompyle6.exe

test: off

artifacts:
 - path: uncompyle6-x86_64.7z
